name: Hugo-CI
on:
  push:
    branches: [master]
    paths-ignore: ".github/**"

jobs:
  job-one:
    name: Deploy
    runs-on: [self-hosted, linux, x64, html-cloud-dev4]
    steps:
      - name: hugo build
        run: |
          cd aspose-html-cloud-docs && git stash && git pull && git submodule update && cd -
          cd lutsk-aspose-prototype && git stash && git pull
          cd themes/lutsk-aspose-theme && git stash && git pull && cd -
          sudo npm install -D --save autoprefixer
          sudo npm install -D --save postcss-cli
          rsync --recursive --delete --force --progress ${{ secrets.PROJECTPATH }} content/
          rm -rf public
          hugo --minify --baseURL https://docs.aspose.cloud/html
          rsync --recursive --delete --force -e "ssh" --progress public/ ${{ secrets.TRANSFERPATH }}
      - name: hugo deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.SSHPORT }}
          script: |
            sudo rsync --recursive --delete --force --progress ${{ secrets.PUBLICCONTENTPATH }} ${{ secrets.DEPLOYPATH }}
            sudo nginx -s reload
